@startuml
participant "Main Function"
participant calculate
participant getInput

activate "Main Function"
"Main Function" -> calculate : 計算実行
activate calculate
calculate -> getInput : 入力を収得
activate getInput
getInput -> calculate : 入力データ
deactivate getInput
calculate -> "Main Function" : 計算結果
deactivate calculate
@enduml


